metaphor:
  metadata:
    version: 1.1
    changes:
      v1.1: Changed answer reference from $OPTION to ANSWER in the prompt template.
  name: metaphor_understanding
  competency: nlu
  dataloader_file: src/dataloaders/huggingface_dataloader.py
  dataloader_class: HuggingFaceDataloader
  metric_file: src/metrics/f1_acc_metric.py
  metric_class: F1AccMetric
  metric: normalized_accuracy
  fewshot_num_examples:
    instruct: 0
    base: 5
  languages:
    id:
      filepath: aisingapore/NLU-Metaphor
      example_filepath: aisingapore/NLU-Metaphor
      max_tokens: 16
      prompt_template:
        preamble: |-
          Jawablah hanya dengan menggunakan format berikut ini:
          "{answer_tag} ANSWER"
          Ganti ANSWER dengan pilihan yang telah dipilih. Gunakan huruf A atau B saja sebagai jawabannya.

          Berdasarkan kalimat yang diberikan, manakah dari pilihan berikut ini yang memiliki arti yang sama?
        task_template: |-
          Kalimat:
          ```
          {phrase}
          ```
          Pilihlah jawaban terbaik dari pilihan di bawah ini:
          A: {choice1}
          B: {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawaban:"
    jv:
      filepath: aisingapore/NLU-Metaphor
      example_filepath: aisingapore/NLU-Metaphor
      max_tokens: 16
      prompt_template:
        preamble: |-
          Jawaben mung nganggo format iki:
          "{answer_tag} ANSWER"
          Ganti ANSWER karo pilihan sing dipilih. Cukup nganggo huruf A utawa B kanggo jawabane.

          Miturut ukara sing diwenehi iki, pilihan ing ngisor iki endi sing nduweni teges padha?
        task_template: |-
          Ukara:
          ```
          {phrase}
          ```
          Pilihen jawaban sing paling cocok saka pilihan iki:
          A: {choice1}
          B: {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawaban:"
    su:
      filepath: aisingapore/NLU-Metaphor
      example_filepath: aisingapore/NLU-Metaphor
      max_tokens: 16
      prompt_template:
        preamble: |-
          Jawap ngan ngagunakeun format di handap ieu:
          "{answer_tag} ANSWER"
          Ganti ANSWER ku jawapan nu geus dipilih. Gunakeun hurup A atawa B salaku jawapan.

          Dumasar kana kalimah anu dipasihkeun, pilihan mana anu sarua hartina?
        task_template: |-
          Kalimah:
          ```
          {phrase}
          ```
          Pilih jawapan anu pangsaena tina pilihan di handap ieu:
          A: {choice1}
          B: {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawaban:"
    ta:
      filepath: aisingapore/NLU-Metaphor
      example_filepath: aisingapore/NLU-Metaphor
      max_tokens: 128
      prompt_template:
        preamble: |-
          நீங்கள் ஒரு தமிழ் மொழியியல் நிபுணர்.

          பின்வரும் வடிவத்தை மட்டும் பயன்படுத்தி பதிலளிக்கவும்:
          "{answer_tag} ANSWER"
          ANSWER ஐ உண்மை அல்லது பொய் என்ற சொற்களுடன் மாற்றவும்.

          இந்த வாக்கியம் மற்றும் அதன் பொருள் உண்மையா அல்லது பொய்யா?
        task_template: |-
          வாக்கியம்: 
          ```
          {metaphor}
          ```
          சாத்தியமான பொருள்:
          ```
          {explanation}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "பதில்:"

metaphor-logprobs:
  metadata: ${metaphor.metadata}
  name: metaphor-logprobs
  competency: ${metaphor.competency}
  dataloader_file: ${metaphor.dataloader_file}
  dataloader_class: ${metaphor.dataloader_class}
  metric_file: src/metrics/logprob_metric.py
  metric_class: LogProbMetric
  metric: average_cumulative_probabilities
  use_logprobs: true
  max_n_runs: 1
  fewshot_num_examples: ${metaphor.fewshot_num_examples}
  languages: ${metaphor.languages}
