sentiment:
  metadata:
    version: 1.1
    changes:
      v1.1: Changed answer reference from $OPTION to ANSWER in the prompt template.
  name: sentiment_analysis
  competency: nlu
  dataloader_file: src/dataloaders/huggingface_dataloader.py
  dataloader_class: HuggingFaceDataloader
  metric_file: src/metrics/f1_acc_metric.py
  metric_class: F1AccMetric
  metric: normalized_accuracy
  fewshot_num_examples:
    instruct: 0
    base: 5
  languages:
    id:
      filepath: aisingapore/NLU-Sentiment-Analysis
      example_filepath: aisingapore/NLU-Sentiment-Analysis
      max_tokens: 32
      prompt_template:
        preamble: |-
          Apa sentimen dari kalimat berikut ini? Gunakan salah satu dari pilihan di bawah ini: Positif, Negatif, atau Netral.

          Jawablah hanya dengan menggunakan format berikut ini:
          "{answer_tag} ANSWER"
          Ganti ANSWER dengan jawaban yang telah dipilih.
        task_template: |-
          Kalimat:
          ```
          {text}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawaban:"
    vi:
      filepath: aisingapore/NLU-Sentiment-Analysis
      example_filepath: aisingapore/NLU-Sentiment-Analysis
      max_tokens: 32
      prompt_template:
        preamble: |-
          Sắc thái của câu sau đây là gì? Trả lời bằng cách sử dụng một trong những lựa chọn sau: Tích cực, Tiêu cực, hoặc Trung lập.

          Chỉ trả lời bằng cách sử dụng định dạng sau:
          "{answer_tag} ANSWER"
          Thay thế ANSWER bằng câu trả lời được chọn.
        task_template: |-
          Câu văn:
          ```
          {text}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Câu trả lời:"
    th:
      filepath: aisingapore/NLU-Sentiment-Analysis
      example_filepath: aisingapore/NLU-Sentiment-Analysis
      max_tokens: 32
      prompt_template:
        preamble: |-
          ประโยคดังต่อไปนี้มีความรู้สึกอย่างไร? ตอบได้แค่ตัวเลือกดังต่อไปนี้: แง่บวก, แง่ลบ, หรือเฉยๆ

          จงตอบตามรูปแบบดังต่อไปนี้:
          "{answer_tag} ANSWER"
          โดยแค่แทนที่ ANSWER ด้วยตัวเลือกของคุณ
        task_template: |-
          ประโยค:
          ```
          {text}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "คำตอบ:"
    ta:
      filepath: aisingapore/NLU-Sentiment-Analysis
      example_filepath: aisingapore/NLU-Sentiment-Analysis
      max_tokens: 32
      prompt_template:
        preamble: |-
          பின்வரும் வாக்கியத்தில் வெளிப்படுத்தப்படும் உணர்வு எது? இந்த சொற்களில் ஒன்றைப் பயன்படுத்தி பதிலளிக்கவும்: நேர்மறை அல்லது எதிர்மறை.

          பின்வரும் பதில் வடிவமைப்பை மட்டும் பயன்படுத்தி பதிலளிக்கவும்:
          "{answer_tag} ANSWER"
          தேர்ந்தெடுக்கப்பட்ட பதிலுடன் ANSWER ஐ மாற்றவும்.
        task_template: |-
          வாக்கியம்:
          ```
          {text}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "பதில்:"
    tl:
      filepath: aisingapore/NLU-Sentiment-Analysis
      example_filepath: aisingapore/NLU-Sentiment-Analysis
      max_tokens: 32
      prompt_template:
        preamble: |-
          Ano ang sentimyento sa sumusunod na pangungusap? Sumagot gamit ng isa sa mga sumusunod na pagpipilian: Positibo, Negatibo, o Neutral.

          Sumagot gamit ang sumusunod na format:
          "{answer_tag} ANSWER"
          Palitan ang ANSWER ng napiling sagot.
        task_template: |-
          Pangungusap:
          ```
          {text}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Sagot:"
    jv:
      filepath: aisingapore/NLU-Sentiment-Analysis
      example_filepath: aisingapore/NLU-Sentiment-Analysis
      max_tokens: 32
      prompt_template:
        preamble: |-
          Apa sentimen saka ukara ing ngisor iki? Pilih salah siji saka pilihan iki: Positif, Negatif, utawa Netral.

          Jawaban mung nganggo format iki:
          "{answer_tag} ANSWER"
          Ganti ANSWER karo jawaban sing dipilih.
        task_template: |-
          Ukara:
          ```
          {text}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawaban:"
    su:
      filepath: aisingapore/NLU-Sentiment-Analysis
      example_filepath: aisingapore/NLU-Sentiment-Analysis
      max_tokens: 32
      prompt_template:
        preamble: |-
          Naon sentimen tina kalimah di handap ieu? Gunakeun salah sahiji pilihan di handap: Positip, Negatip, atawa Netral.

          Jawap ngan ngagunakeun format di handap ieu:
          "{answer_tag} ANSWER"
          Ganti ANSWER ku jawapan nu geus dipilih.
        task_template: |-
          Kalimah:
          ```
          {text}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawaban:"
    ms:
      filepath: aisingapore/NLU-Sentiment-Analysis
      example_filepath: aisingapore/NLU-Sentiment-Analysis
      max_tokens: 32
      prompt_template:
        preamble: |-
          Apakah sentimen ayat berikut? Gunakan salah satu pilihan di bawah: Positif, Negatif, atau Netral.

          Jawab hanya menggunakan format berikut:
          "{answer_tag} ANSWER"
          Gantikan ANSWER dengan jawapan yang dipilih.
        task_template: |-
          Ayat:
          ```
          {text}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawapan:"
    my:
      filepath: aisingapore/NLU-Sentiment-Analysis
      example_filepath: aisingapore/NLU-Sentiment-Analysis
      max_tokens: 32
      prompt_template:
        preamble: |-
          အောက်ပါဝါကျ၏ စိတ်ခံစားချက် (sentiment) မှာ အဘယ်နည်း။ အောက်ပါ ရွေးချယ်စရာများထဲမှ တစ်ခုကို သုံးပါ: အပြုသဘော, အပျက်သဘော, သို့မဟုတ် ကြားနေ။

          အောက်ဖော်ပြပါ ပုံစံကိုသာ အသုံးပြု၍ ဖြေဆိုပါ-
          "{answer_tag} ANSWER"
          ANSWER နေရာတွင် သင်ရွေးချယ်ထားသော အဖြေကို အစားထိုးထည့်ပါ။
        task_template: |-
          ဝါကျ-
          ```
          {text}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "အဖြေ-"
    lo:
      filepath: aisingapore/NLU-Sentiment-Analysis
      example_filepath: aisingapore/NLU-Sentiment-Analysis
      max_tokens: 32
      prompt_template:
        preamble: |-
          ປະໂຫຍກຕໍ່ໄປນີ້ມີຄວາມຮູ້ສຶກແນວໃດ? ຕອບໄດ້ພຽງແຕ່ຕົວເລືອກດັ່ງຕໍ່ໄປນີ້: ແງ່ບວກ ຫຼື ແງ່ລົບ

          ຈົ່ງຕອບຕາມຮູບແບບດັ່ງຕໍ່ໄປນີ້:
          "{answer_tag} ANSWER"
          ໂດຍພຽງແຕ່ແທນທີ່ ANSWER ດ້ວຍຕົວເລືອກຂອງທ່ານ
        task_template: |-
          ປະໂຫຍກ:
          ```
          {text}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "ຄຳຕອບ:"

sentiment-logprobs:
  metadata: ${sentiment.metadata}
  name: sentiment-logprobs
  competency: ${sentiment.competency}
  dataloader_file: ${sentiment.dataloader_file}
  dataloader_class: ${sentiment.dataloader_class}
  metric_file: src/metrics/logprob_metric.py
  metric_class: LogProbMetric
  metric: average_cumulative_probabilities
  use_logprobs: true
  max_n_runs: 1
  fewshot_num_examples: ${sentiment.fewshot_num_examples}
  languages: ${sentiment.languages}
