causal:
  metadata:
    version: 1.1
    changes:
      v1.1: Changed answer reference from $OPTION to ANSWER in the prompt template.
  name: causal_reasoning
  competency: nlr
  dataloader_file: src/dataloaders/huggingface_dataloader.py
  dataloader_class: HuggingFaceDataloader
  metric_file: src/metrics/f1_acc_metric.py
  metric_class: F1AccMetric
  metric: normalized_accuracy
  fewshot_num_examples:
    instruct: 0
    base: 5
  languages:
    zh:
      filepath: aisingapore/NLR-Causal-Reasoning
      example_filepath: aisingapore/NLR-Causal-Reasoning
      max_tokens: 128
      prompt_template:
        preamble: |-
          请仅使用以下格式回答：
          "{answer_tag} 答案"
          将“答案”替换为你选择的选项。仅使用字母 A 或 B 作为回答。
        task_template: |-
          根据所给情境，以下哪一选项最有可能是{question_translated}？

          情境：
          ```
          {premise}
          ```
          从以下选项中选择最佳答案：
          A: {choice1}
          B: {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "答案"
    id:
      filepath: aisingapore/NLR-Causal-Reasoning
      example_filepath: aisingapore/NLR-Causal-Reasoning
      max_tokens: 128
      prompt_template:
        preamble: |-
          Jawablah hanya dengan menggunakan format berikut ini:
          "{answer_tag} ANSWER"
          Ganti ANSWER dengan pilihan yang telah dipilih. Gunakan huruf A atau B saja sebagai jawabannya.
        task_template: |-
          Berdasarkan situasi yang diberikan, manakah dari pilihan berikut ini yang lebih mungkin menjadi {question_translated}?

          Situasi:
          ```
          {premise}
          ```
          Pilihlah jawaban yang terbaik dari pilihan di bawah ini:
          A: {choice1}
          B: {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawaban:"
    vi:
      filepath: aisingapore/NLR-Causal-Reasoning
      example_filepath: aisingapore/NLR-Causal-Reasoning
      max_tokens: 128
      prompt_template:
        preamble: |-
          Chỉ trả lời bằng cách sử dụng định dạng sau:
          "{answer_tag} ANSWER"
          Thay thế ANSWER bằng câu trả lời được chọn. Chỉ sử dụng chữ cái A hoặc B làm câu trả lời của bạn.
        task_template: |-
          Với tình huống trên, lựa chọn nào dưới đây có khả năng cao là {question_translated} của nó hơn?

          Tình huống:
          ```
          {premise}
          ```
          Chọn đáp án tốt nhất trong các lựa chọn sau:
          A: {choice1}
          B: {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Câu trả lời:"
    th:
      filepath: aisingapore/NLR-Causal-Reasoning
      example_filepath: aisingapore/NLR-Causal-Reasoning
      max_tokens: 128
      prompt_template:
        preamble: |-
          จงตอบตามรูปแบบดังต่อไปนี้:
          "{answer_tag} ANSWER"
          โดยจะต้องแทนที่ ANSWER ด้วยคำตอบของคุณด้วยตัวอักษร A หรือ B เท่านั้น
        task_template: |-
          จากสถานการณ์ที่กำลังจะยกให้ ตัวเลือกใดต่อไปนี้ตรงกับ{question_translated}มากที่สุด?

          สถานการณ์:
          ```
          {premise}
          ```
          จงเลือกคำตอบที่ดีที่สุดจากตัวเลือกต่อไปนี้:
          A: {choice1}
          B: {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "คำตอบ:"
    ta:
      filepath: aisingapore/NLR-Causal-Reasoning
      example_filepath: aisingapore/NLR-Causal-Reasoning
      max_tokens: 128
      prompt_template:
        preamble: |-
          பின்வரும் பதில் வடிவமைப்பை மட்டும் பயன்படுத்தி பதிலளிக்கவும்:
          "{answer_tag} ANSWER"
          தேர்ந்தெடுக்கப்பட்ட பதிலுடன் ANSWER ஐ மாற்றவும். A அல்லது B என்ற எழுத்துக்களில் மட்டும் பதிலளிக்கவும்.
        task_template: |-
          கொடுக்கப்பட்ட சூழ்நிலையின் அடிப்படையில், பின்வரும் வாக்கியங்களில் பெரும்பாலும் எது {question_translated} இருக்கும்?

          சூழ்நிலை:
          ```
          {premise}
          ```
          பின்வரும் வாக்கியங்களிலிருந்து சிறந்த பதிலைத் தேர்ந்தெடுக்கவும்:
          A: {choice1}
          B: {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "பதில்:"
    tl:
      filepath: aisingapore/NLR-Causal-Reasoning
      example_filepath: aisingapore/NLR-Causal-Reasoning
      max_tokens: 128
      prompt_template:
        preamble: |-
          Sumagot gamit ang sumusunod na format:
          "{answer_tag} ANSWER"
          Palitan ang ANSWER gamit ang napiling sagot. Gumamit lang ng letrang A or B sa sagot mo.
        task_template: |-
          Batay sa ibibigay na sitwasyon, alin sa sumusunod na pagpipilian ang mas maaari na {question_translated}?

          Sitwasyon:
          ```
          {premise}
          ```
          Piliin ang pinaka-angkop na sagot mula sa sumusunod na pagpipilian:
          A: {choice1}
          B: {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Sagot:"
    my:
      filepath: aisingapore/NLR-Causal-Reasoning
      example_filepath: aisingapore/NLR-Causal-Reasoning
      max_tokens: 128
      prompt_template:
        preamble: |-
          အောက်ဖော်ပြပါ ပုံစံကိုသာ အသုံးပြု၍ ဖြေဆိုပါ:
          "{answer_tag} ANSWER"
          ANSWER နေရာတွင် သင်ရွေးချယ်ထားသော အဖြေကို အစားထိုးထည့်ပါ။ အဖြေအတွက် က သို့မဟုတ် ခ အက္ခရာကို အသုံးပြုပါ။
        task_template: |-
          ပေးထားသော အခြေအနေကို အခြေခံ၍ အောက်ပါရွေးချယ်စရာများထဲမှ မည်သည့်အရာက {question_translated} ဖြစ်နိုင်ခြေပိုများပါသလဲ။

          အခြေအနေ-
          ```
          {premise}
          ```
          အောက်ပါရွေးချယ်စရာများမှ အကောင်းဆုံးအဖြေကို ရွေးချယ်ပါ-
          က- {choice1}
          ခ- {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "အဖြေ-"
    ms:
      filepath: aisingapore/NLR-Causal-Reasoning
      example_filepath: aisingapore/NLR-Causal-Reasoning
      max_tokens: 128
      prompt_template:
        preamble: |-
          Jawab guna format ini sahaja:
          "{answer_tag} ANSWER"
          Gantikan ANSWER dengan pilihan yang dipilih. Gunakan huruf A atau B sebagai jawapan.
        task_template: |-
          Berdasarkan situasi yang diberikan, yang manakah antara pilihan berikut lebih mungkin menjadi {question_translated}?

          Situasi:
          ```
          {premise}
          ```
          Pilih jawapan terbaik daripada pilihan berikut:
          A: {choice1}
          B: {choice2}
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawapan:"

causal-logprobs:
  metadata: ${causal.metadata}
  name: causal-logprobs
  competency: ${causal.competency}
  dataloader_file: ${causal.dataloader_file}
  dataloader_class: ${causal.dataloader_class}
  metric_file: src/metrics/logprob_metric.py
  metric_class: LogProbMetric
  metric: average_cumulative_probabilities
  use_logprobs: true
  max_n_runs: 1
  fewshot_num_examples: ${causal.fewshot_num_examples}
  languages: ${causal.languages}
