nli:
  metadata:
    version: 1.1
    changes:
      v1.1: Changed answer reference from $OPTION to ANSWER in the prompt template.
  name: natural_language_inference
  competency: nlr
  dataloader_file: src/dataloaders/huggingface_dataloader.py
  dataloader_class: HuggingFaceDataloader
  metric_file: src/metrics/f1_acc_metric.py
  metric_class: F1AccMetric
  metric: normalized_accuracy
  fewshot_num_examples:
    instruct: 0
    base: 5
  languages:
    id:
      filepath: aisingapore/NLR-NLI
      example_filepath: aisingapore/NLR-NLI
      max_tokens: 128
      prompt_template:
        preamble: |-
          Anda akan diberikan dua kalimat, SENTENCE_1 dan SENTENCE_2. Tentukan mana dari pernyataan berikut ini yang paling sesuai untuk kalimat SENTENCE_1 dan SENTENCE_2.
          A: Jika SENTENCE_1 benar, maka SENTENCE_2 juga harus benar.
          B: SENTENCE_1 bertentangan dengan SENTENCE_2.
          C: Ketika SENTENCE_1 benar, SENTENCE_2 mungkin saja benar atau tidak benar.

          Jawablah hanya dengan menggunakan format berikut ini:
          "{answer_tag} ANSWER"
          Ganti ANSWER dengan pilihan yang telah dipilih. Gunakan huruf A, B, atau C saja sebagai jawabannya.
        task_template: |-
          SENTENCE_1:
          ```
          {sentence1}
          ```
          SENTENCE_2:
          ```
          {sentence2}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawaban:"
    vi:
      filepath: aisingapore/NLR-NLI
      example_filepath: aisingapore/NLR-NLI
      max_tokens: 128
      prompt_template:
        preamble: |-
          Bạn sẽ được cho hai câu, SENTENCE_1 và SENTENCE_2.
          Xác định mệnh đề nào sau đây là phù hợp nhất cho câu SENTENCE_1 và SENTENCE_2.
          A: Nếu SENTENCE_1 đúng thì SENTENCE_2 phải đúng.
          B: SENTENCE_1 mâu thuẫn với SENTENCE_2.
          C: Khi SENTENCE_1 đúng, SENTENCE_2 có thể đúng hoặc không đúng.

          Chỉ trả lời bằng cách sử dụng định dạng sau:
          "{answer_tag} ANSWER"
          Thay thế ANSWER bằng câu trả lời được chọn. Chỉ sử dụng chữ cái A, B hoặc C làm câu trả lời của bạn.
        task_template: |-
          SENTENCE_1:
          ```
          {sentence1}
          ```
          SENTENCE_2:
          ```
          {sentence2}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Câu trả lời:"
    th:
      filepath: aisingapore/NLR-NLI
      example_filepath: aisingapore/NLR-NLI
      max_tokens: 128
      prompt_template:
        preamble: |-
          คุณจะได้รับประโยค 2 ประโยค ได้แก่ SENTENCE_1 และ SENTENCE_2 จงพิจารณาว่า ข้อความใดต่อไปนี้เหมาะสมกับ SENTENCE_1 และ SENTENCE_2 มากที่สุด
          A: ถ้า SENTENCE_1 เป็นจริง งั้น SENTENCE_2 ก็ต้องเป็นจริง
          B: SENTENCE_1 ขัดแย้งกับ SENTENCE_2
          C: เมื่อ SENTENCE_1 เป็นจริง งั้น SENTENCE_2 อาจะเป็นจริงหรือไม่เป็นจริงก็ได้

          จงตอบตามรูปแบบดังต่อไปนี้:
          "{answer_tag} ANSWER"
          โดยแทนที่ ANSWER ด้วยตัวเลือกของคุณด้วยตัวอักษร A, B, หรือ C เท่านั้น
        task_template: |-
          SENTENCE_1:
          ```
          {sentence1}
          ```
          SENTENCE_2:
          ```
          {sentence2}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "คำตอบ:"
    ta:
      filepath: aisingapore/NLR-NLI
      example_filepath: aisingapore/NLR-NLI
      max_tokens: 128
      prompt_template:
        preamble: |-
          உங்களுக்கு இரண்டு வாக்கியங்கள், SENTENCE_1 மற்றும் SENTENCE_2 கொடுக்கப்படும்.
          பின்வரும் கூற்றுகளில் எது SENTENCE_1 மற்றும் SENTENCE_2 வாக்கியங்களுடன் மிகப் பொருந்துகிறது எனக் கண்டறியவும்.
          A: SENTENCE_1 உண்மை என்றால் SENTENCE_2 உம் உண்மையாக இருக்க வேண்டும்.
          B: SENTENCE_1 உம் SENTENCE_2 உம் முரண்படுகின்றன.
          C: SENTENCE_1 உண்மையாக இருக்கும்போது SENTENCE_2 உண்மையாக இருக்கலாம் அல்லது இல்லாமல் இருக்கலாம்.

          பின்வரும் பதில் வடிவமைப்பை மட்டும் பயன்படுத்தி பதிலளிக்கவும்:
          "{answer_tag} ANSWER"
          தேர்ந்தெடுக்கப்பட்ட பதிலுடன் ANSWER ஐ மாற்றவும். A அல்லது B அல்லது C என்ற எழுத்துக்களில் மட்டும் பதிலளிக்கவும்.
        task_template: |-
          SENTENCE_1:
          ```
          {sentence1}
          ```
          SENTENCE_2:
          ```
          {sentence2}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "பதில்:"
    tl:
      filepath: aisingapore/NLR-NLI
      example_filepath: aisingapore/NLR-NLI
      max_tokens: 128
      prompt_template:
        preamble: |-
          Bibigyan ka ng dalawang pangungusap, SENTENCE_1 at SENTENCE_2. Tukuyin kung alin sa sumusunod na pahayag ang pinaka-angkop para sa SENTENCE_1 at SENTENCE_2.
          A: Kung totoo ang SENTENCE_1, dapat totoo din ang SENTENCE_2.
          B: Sumasalungat ang SENTENCE_1 sa SENTENCE_2.
          C: Kapag totoo ang SENTENCE_1, pwedeng totoo o hindi totoo ang SENTENCE_2.

          Sumagot gamit ang sumusunod na format.
          "{answer_tag} ANSWER"
          Palitan ang ANSWER ng napiling sagot. Gumamit lang ng titik A, B, o C sa sagot mo.
        task_template: |-
          SENTENCE_1:
          ```
          {sentence1}
          ```
          SENTENCE_2:
          ```
          {sentence2}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Sagot:"
    my:
      filepath: aisingapore/NLR-NLI
      example_filepath: aisingapore/NLR-NLI
      max_tokens: 128
      prompt_template:
        preamble: |-
          သင့်ကို SENTENCE_1 နှင့် SENTENCE_2 ဟူသော ဝါကျစာကြောင်း နှစ်ခုကို ပေးထားပါမည်။ SENTENCE_1 နှင့် SENTENCE_2 တို့အတွက် အောက်ပါဖော်ပြချက်များထဲမှ မည်သည့်အချက်က အကောင်းဆုံး ကိုက်ညီမှုရှိသည်ကို ဆုံးဖြတ်ပါ။
          က- SENTENCE_1 မှန်ကန်လျှင် SENTENCE_2 သည် မုချမှန်ကန်ရမည်။
          ခ- SENTENCE_1 သည် SENTENCE_2 ကို ဆန့်ကျင်သည်။
          ဂ- SENTENCE_1 မှန်ကန်သောအခါ၊ SENTENCE_2 သည် မှန်ကန်နိုင်သလို မမှန်ကန်ဘဲလည်း ရှိနိုင်ပါသည်။

          အောက်ဖော်ပြပါ ပုံစံကိုသာ အသုံးပြု၍ ဖြေဆိုပါ-
          "{answer_tag} ANSWER"
          ANSWER နေရာတွင် သင်ရွေးချယ်ထားသော အဖြေကို အစားထိုးထည့်ပါ။ အဖြေအတွက် က၊ ခ သို့မဟုတ် ဂ အက္ခရာကို အသုံးပြုပါ။
        task_template: |-
          SENTENCE_1-
          ```
          {sentence1}
          ```
          SENTENCE_2-
          ```
          {sentence2}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "အဖြေ:"
    ms:
      filepath: aisingapore/NLR-NLI
      example_filepath: aisingapore/NLR-NLI
      max_tokens: 128
      prompt_template:
        preamble: |-
          Anda akan diberikan dua ayat, SENTENCE_1 dan SENTENCE_2. Tentukan yang manakah antara kenyataan berikut yang paling sesuai untuk SENTENCE_1 dan SENTENCE_2.
          A: Jika SENTENCE_1 benar, SENTENCE_2 mesti benar.
          B: SENTENCE_1 bercanggah dengan SENTENCE_2.
          C: Apabila SENTENCE_1 benar, SENTENCE_2 mungkin atau mungkin tidak benar.

          Jawab guna format ini sahaja:
          "{answer_tag} ANSWER"
          Gantikan ANSWER dengan pilihan yang dipilih. Gunakan huruf A, B, atau C sebagai jawapan.
        task_template: |-
          SENTENCE_1:
          ```
          {sentence1}
          ```
          SENTENCE_2:
          ```
          {sentence2}
          ```
        answer_template: |-
          {answer_tag} {label}
        answer_tag: "Jawapan:"

nli-logprobs:
  metadata: ${nli.metadata}
  name: nli-logprobs
  competency: ${nli.competency}
  dataloader_file: ${nli.dataloader_file}
  dataloader_class: ${nli.dataloader_class}
  metric_file: src/metrics/logprob_metric.py
  metric_class: LogProbMetric
  metric: average_cumulative_probabilities
  use_logprobs: true
  max_n_runs: 1
  fewshot_num_examples: ${nli.fewshot_num_examples}
  languages: ${nli.languages}
